# Purrify Machine-Specific Optimization Script (PowerShell)
# Generated by Purrify with LilithOS technology
$ErrorActionPreference = 'Stop'
Write-Host 'Running Purrify system optimizations...' -ForegroundColor Cyan
# Disable unnecessary startup items
Get-CimInstance Win32_StartupCommand | Where-Object { $_.Location -notlike '*Windows*' } | ForEach-Object { Write-Host 'Disabling:' $_.Name; Remove-ItemProperty -Path $_.Command -Name $_.Name -ErrorAction SilentlyContinue }
# Set unnecessary services to Manual
$services = @('DiagTrack','MapsBroker','WSearch','Fax','XblGameSave','XboxNetApiSvc','WMPNetworkSvc')
foreach ($svc in $services) { Set-Service -Name $svc -StartupType Manual -ErrorAction SilentlyContinue }
# Windows 11 performance registry tweaks
Set-ItemProperty -Path 'HKCU:Software\Microsoft\Windows\CurrentVersion\Explorer\Serialize' -Name 'StartupDelayInMSec' -Value 0 -Force
Set-ItemProperty -Path 'HKLM:SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'EnableLUA' -Value 0 -Force
# Clean up temp files and system cache
Remove-Item -Path $env:TEMP\* -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path C:\Windows\Temp\* -Recurse -Force -ErrorAction SilentlyContinue
# LilithOS-specific optimizations
# Clean LilithOS cache: C:/LilithOS
Remove-Item -Path 'C:/LilithOS\*' -Recurse -Force -ErrorAction SilentlyContinue
# Clean LilithOS cache: C:/Program Files/LilithOS
Remove-Item -Path 'C:/Program Files/LilithOS\*' -Recurse -Force -ErrorAction SilentlyContinue
# Clean LilithOS cache: C:\Users\sunny/LilithOS
Remove-Item -Path 'C:\Users\sunny/LilithOS\*' -Recurse -Force -ErrorAction SilentlyContinue
# Remove redundant folders
Remove-Item -Path 'C:\LilithOS\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\LilithOS\.git\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\LilithOS_Installer\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\msys64\tmp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\msys64\var\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\msys64\var\tmp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\msys64\var\log\old' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Program Files (x86)\ASUS\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Program Files (x86)\Common Files\Adobe\Adobe PCD\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Program Files (x86)\Epic Games\Launcher\Engine\Content\Slate\Old' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Program Files (x86)\Epic Games\Launcher\Portal\Content\UI\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Program Files (x86)\Microsoft\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Program Files (x86)\Mozilla Maintenance Service\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Program Files (x86)\Steam\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Program Files (x86)\Steam\steamapps\temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Program Files (x86)\Steam\steamapps\workshop\temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Program Files (x86)\Steam\userdata\69028321\ugc\temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Program Files (x86)\Ubisoft\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Program Files (x86)\Ubisoft\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\Default\AppData\Local\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\Default\AppData\Local\Logi\LogiPluginService\Logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\$PHANTOM_ROOT\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\.amplify\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\.cargo\registry\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\regex-1.10.2\record\old-bench-log\old' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\regex-1.10.4\record\old-bench-log\old' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\.cursor\extensions\ms-python.python-2025.6.1-win32-x64\python_files\lib\jedilsp\jedi\third_party\django-stubs\django-stubs\core\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\.cursor\extensions\ms-python.vscode-pylance-2024.8.1\dist\bundled\stubs\django-stubs\core\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\.nx\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\.nx\temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\.rustup\tmp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\.windsurf\extensions\ms-python.python-2025.0.0-universal\python_files\lib\jedilsp\jedi\third_party\django-stubs\django-stubs\core\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Backup' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Adobe\webview2\Creative_Cloud_Set-Up.exe\EBWebView\Default\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Adobe\webview2\Creative_Cloud_Set-Up.exe\EBWebView\Default\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Android\Sdk\sources\android-35\android\app\backup' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Android\Sdk\sources\android-35\com\android\server\backup' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\CefSharp\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\CefSharp\Cache\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\CefSharp\Cache\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\checkpoint-nodejs\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\CrashReportClient\Saved\Logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Cypress\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Cypress\Cache\12.17.4\Cypress\resources\app\node_modules\tmp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Cypress\Cache\12.17.4\Cypress\resources\app\node_modules\tsconfig-paths-webpack-plugin\temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Cypress\Cache\12.17.4\Cypress\resources\app\node_modules\webpack\lib\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Discord\app-1.0.9194\modules\discord_krisp-1\discord_krisp\KMS\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\electron\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\EpicGamesLauncher\Saved\Logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\EpicGamesLauncher\Saved\webcache_4430\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\flutter_webview_windows\LogiAiPromptBuilder\EBWebView\Default\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\flutter_webview_windows\LogiAiPromptBuilder\EBWebView\Default\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\FortniteGame\Saved\Logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Google\AndroidStudio2024.2\tmp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\hardhat-nodejs\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Logi\LogiPluginService\Logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Logi\LogiPluginService\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Microsoft\Azure DevOps\8.0\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Microsoft\Edge\User Data\Default\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Microsoft\Edge\User Data\Default\Continuous Migration\Logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Microsoft\Edge\User Data\Default\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Microsoft\Edge\User Data\Default\Storage\ext\ihmafllikibpmigkcoadcmckbfhibefp\def\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Microsoft\Edge\User Data\Default\Storage\ext\ihmafllikibpmigkcoadcmckbfhibefp\def\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Microsoft\Edge\User Data\Default\Sync Data\Logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Microsoft\Edge\User Data\Default\Web Applications\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Microsoft\Edge\User Data\Default\Workspaces\Logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Microsoft\Office\16.0\Wef\webview2\9b6405fd7479711f_LiveId\1\EBWebView\Default\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Microsoft\Office\16.0\Wef\webview2\9b6405fd7479711f_LiveId\1\EBWebView\Default\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Microsoft\Office\16.0\Wef\webview2\ec100f45357a3698_LiveId\2\EBWebView\Default\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Microsoft\Office\16.0\Wef\webview2\ec100f45357a3698_LiveId\2\EBWebView\Default\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Microsoft\Olk\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Microsoft\Olk\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Microsoft\Olk\EBWebView\Default\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Microsoft\Olk\EBWebView\Default\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Microsoft\OneDrive\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Microsoft\OneDrive\setup\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Microsoft\OneNote\16.0\Backup' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Microsoft\OneNote\16.0\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Microsoft\OneNote\16.0\cache\tmp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Microsoft\Terminal Server Client\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Microsoft\TokenBroker\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Microsoft\WindowsApps\Backup' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\node-gyp\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\npm-cache\_cacache\tmp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\npm-cache\_npx\04c5e9b9c9ed137e\node_modules\tmp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\npm-cache\_npx\04c5e9b9c9ed137e\node_modules\@smithy\util-endpoints\dist-cjs\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\npm-cache\_npx\04c5e9b9c9ed137e\node_modules\@smithy\util-endpoints\dist-es\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\npm-cache\_npx\04c5e9b9c9ed137e\node_modules\@smithy\util-endpoints\dist-types\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\npm-cache\_npx\04c5e9b9c9ed137e\node_modules\@smithy\util-endpoints\dist-types\ts3.4\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\npm-cache\_npx\c67e74de0542c87c\node_modules\tmp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\NVIDIA Corporation\NVIDIA app\CefCache\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\NVIDIA Corporation\NVIDIA app\CefCache\Default\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\NVIDIA Corporation\NVIDIA app\CefCache\Default\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\NVIDIA Corporation\NVIDIA GeForce Experience\CefCache\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\NVIDIA Corporation\NVIDIA Notification\CefCache\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\NVIDIA Corporation\NVIDIA Overlay\CefCache\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\NVIDIA Corporation\NVIDIA Overlay\CefCache\Default\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\NVIDIA Corporation\NVIDIA Overlay\CefCache\Default\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\NVIDIA Corporation\NVIDIA Share\CefCache\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\OneDrive\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\1527c705-839a-4832-9118-54d4Bd6a0c89_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\AdobeNotificationClient_enpm4xejd91yc\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\AppleInc.iCloud_nzyj5cx40ttqa\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\AppleInc.iCloud_nzyj5cx40ttqa\LocalCache\Local\Logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\AppleInc.iCloud_nzyj5cx40ttqa\LocalCache\Local\WebViewUserDataDirs\iCloudHome\EBWebView\Default\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\AppleInc.iCloud_nzyj5cx40ttqa\LocalCache\Roaming\Apple Computer\Logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\AppleInc.iTunes_nzyj5cx40ttqa\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\AppleInc.iTunes_nzyj5cx40ttqa\LocalCache\Local\Apple Inc\Logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\AppleInc.iTunes_nzyj5cx40ttqa\LocalCache\Roaming\Apple Computer\Logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\AppUp.IntelGraphicsExperience_8j3eq9eme6ctt\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\ASUSAmbientHAL64_ecvjzhf6c4w7r\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\B9ECED6F.ArmouryCrate_qmba6cd70vzyy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\B9ECED6F.ArmouryCrate_qmba6cd70vzyy\AC\#!sb.odm\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\B9ECED6F.ArmouryCrate_qmba6cd70vzyy\LocalState\EBWebView\Default\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\B9ECED6F.ArmouryCrate_qmba6cd70vzyy\LocalState\EBWebView\Default\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\B9ECED6F.ArmouryCrate_qmba6cd70vzyy\LocalState\GameLibrary\LocalData\backup' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\B9ECED6F.ArmouryCrate_qmba6cd70vzyy\LocalState\GameLibrary\LocalData\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\B9ECED6F.ArmouryCrate_qmba6cd70vzyy\LocalState\MacroFiles\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\B9ECED6F.ASUSPCAssistant_qmba6cd70vzyy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\B9ECED6F.AURACreator_qmba6cd70vzyy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\B9ECED6F.Glidex_qmba6cd70vzyy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\c5e2524a-ea46-4f67-841f-6a9465d9d515_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu_79rhkp1fndgsc\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\cr.sb.cdmcd117dc077c81dc967e32210a03365803d3555f0\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\cr.sb.odm05C470C4C479D442FFBAEC30E3779E889BD46418\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\cr.sb.odm33DF9CD9D0AD4CC46FEE306018ABDE7BF471E03D\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\cr.sb.odm66398AA66CAE854632A21ACCC2616AC908F11276\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\cr.sb.odm7477C6182CC3E054673B583CF96E1BC87A46259B\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\cr.sb.odm89F08B5D0CDF768A7A51666341F2F70D395B1DBD\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\cr.sb.odm9371DFC2582375F0E7A72FE7D40DC3DF7F8D3CBF\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\cr.sb.odm982A88884E7517B7151097F7EA2381F7701F3F04\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\cr.sb.odm9A0439F4590207C91256D48E8591D2F87960A38A\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\cr.sb.odmd8dfbc5aa947da104644eb41b50cc3e5f48fb5a9\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\cr.sb.odmeecc7f22c796e6e2ec0afe58069ea1e322a97c81\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\cr.sb.odmf5200eafd3ad904629cbb0f87a78a3c7211081fe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\cr.sb.odmF97023541EC0ED4DE0B01238923263C7717A7039\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\DolbyLaboratories.DolbyAccess_rz1tebttyb220\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\DolbyLaboratories.DolbyDigitalPlusDecoderOEM_rz1tebttyb220\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\DolbyLaboratories.DolbyVisionAccess_rz1tebttyb220\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\E2A4F912-2574-4A75-9BB0-0D023378592B_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Exafunction.Windsurf_ebj5frz4mxjwy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\F46D4000-FD22-4DB4-AC8E-4E1DDDE828FE_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\flipclock.app-D9B00968_k6dkhgfe7f68j\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\fx.sb.cdmaead3483b5e3a557227b77554c4d4739fd53e90f\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\KaliLinux.54290C8133FEE_ey8k8hqnwqnmg\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\LGElectronics.LGMonitorApp_cfnzzhwkr8z5w\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.6365217CE6EB4_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.6365217CE6EB4_8wekyb3d8bbwe\LocalCache\WebView\EBWebView\Default\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.6365217CE6EB4_8wekyb3d8bbwe\LocalCache\WebView\EBWebView\Default\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.6365217CE6EB4_8wekyb3d8bbwe\LocalState\Logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.AAD.BrokerPlugin_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.AccountsControl_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.ApplicationCompatibilityEnhancements_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.AsyncTextService_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.AV1VideoExtension_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.AVCEncoderVideoExtension_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.BingNews_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.BingSearch_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.BingWeather_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.BioEnrollment_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.Copilot_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.CredDialogHost_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.DirectXRuntime_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.ECApp_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.Edge.GameAssist_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\AC\TokenBroker\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\LocalState\Logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\LocalState\EBWebView\Default\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.GamingApp_8wekyb3d8bbwe\LocalState\EBWebView\Default\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.GamingServices_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.GamingServices_8wekyb3d8bbwe\LocalState\EBWebView\Default\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.GamingServices_8wekyb3d8bbwe\LocalState\EBWebView\Default\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.GetHelp_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.GetHelp_8wekyb3d8bbwe\LocalState\EBWebView\Default\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.GetHelp_8wekyb3d8bbwe\LocalState\EBWebView\Default\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.HEIFImageExtension_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.HEVCVideoExtension_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.LockApp_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.MicrosoftEdge.Stable_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.MicrosoftEdgeDevToolsClient_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.MicrosoftOfficeHub_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.MicrosoftOfficeHub_8wekyb3d8bbwe\LocalState\EBWebView\Default\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.MicrosoftOfficeHub_8wekyb3d8bbwe\LocalState\EBWebView\Default\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.MicrosoftStickyNotes_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.MicrosoftStickyNotes_8wekyb3d8bbwe\AC\TokenBroker\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.MPEG2VideoExtension_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.NET.Native.Framework.2.2_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.NET.Native.Runtime.2.2_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.Office.OneNoteVirtualPrinter_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.OfficePushNotificationUtility_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.OneDriveSync_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.OutlookForWindows_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.OutlookForWindows_8wekyb3d8bbwe\AC\#!sb.odm\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.Paint_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.People_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.PowerAutomateDesktop_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.RawImageExtension_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.ScreenSketch_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.SecHealthUI_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.Services.Store.Engagement_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.StorePurchaseApp_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.StorePurchaseApp_8wekyb3d8bbwe\AC\TokenBroker\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.Todos_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.UI.Xaml.2.7_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.UI.Xaml.2.8_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.VCLibs.110.00.UWPDesktop_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.VCLibs.120.00.UWPDesktop_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.VCLibs.140.00.UWPDesktop_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.VCLibs.140.00_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.VP9VideoExtensions_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.WebMediaExtensions_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.WebpImageExtension_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.WidgetsPlatformRuntime_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.Win32WebViewHost_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.Windows.Apprep.ChxApp_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.Windows.CapturePicker_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.Windows.CloudExperienceHost_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.Windows.ContentDeliveryManager_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.Windows.ContentDeliveryManager_cw5n1h2txyewy\AC\TokenBroker\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.Windows.DevHome_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.Windows.NarratorQuickStart_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.Windows.ParentalControls_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.Windows.PeopleExperienceHost_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.Windows.Photos_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.Windows.Photos_8wekyb3d8bbwe\LocalState\EBWebView\Default\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.Windows.Photos_8wekyb3d8bbwe\LocalState\EBWebView\Default\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.Windows.PinningConfirmationDialog_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.Windows.PrintQueueActionCenter_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.Windows.ShellExperienceHost_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\AC\TokenBroker\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.Windows.XGpuEjectDialog_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.WindowsAlarms_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.WindowsAppRuntime.1.1_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.WindowsAppRuntime.1.2_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.WindowsAppRuntime.1.4_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.WindowsAppRuntime.1.5_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.WindowsAppRuntime.1.6_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.WindowsAppRuntime.1.7_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.WindowsCalculator_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.WindowsCamera_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\microsoft.windowscommunicationsapps_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\microsoft.windowscommunicationsapps_8wekyb3d8bbwe\AC\TokenBroker\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.WindowsFeedbackHub_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.WindowsMaps_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.WindowsNotepad_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.WindowsSoundRecorder_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.WindowsStore_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.WindowsStore_8wekyb3d8bbwe\AC\TokenBroker\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.Winget.Source_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.Xbox.TCUI_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.XboxGameCallableUI_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.XboxGameOverlay_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.XboxGamingOverlay_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.XboxGamingOverlay_8wekyb3d8bbwe\LocalState\Logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.XboxIdentityProvider_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.XboxIdentityProvider_8wekyb3d8bbwe\AC\TokenBroker\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.XboxSpeechToTextOverlay_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.YourPhone_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.ZuneMusic_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Microsoft.ZuneVideo_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\MicrosoftCorporationII.MicrosoftFamily_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\MicrosoftCorporationII.QuickAssist_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\MicrosoftCorporationII.WindowsSubsystemForLinux_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\MicrosoftTeams_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\AC\#!sb.odm\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\AC\TokenBroker\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\LocalState\EBWebView\Default\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\LocalState\EBWebView\Default\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\MicrosoftWindows.Client.CoreAI_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\MicrosoftWindows.Client.OOBE_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\MicrosoftWindows.Client.WebExperience_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\MicrosoftWindows.Client.WebExperience_cw5n1h2txyewy\LocalState\EBWebView\Default\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\MicrosoftWindows.Client.WebExperience_cw5n1h2txyewy\LocalState\EBWebView\Default\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\MicrosoftWindows.CrossDevice_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\MSTeams_8wekyb3d8bbwe\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\mtr.e8markets.com-77A28EF6_s23azfp7f4ddr\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\NVIDIACorp.NVIDIAControlPanel_56jybvy8sckqj\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\OpenAI.ChatGPT-Desktop_2p2nqsd0c76g0\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\OpenAI.ChatGPT-Desktop_2p2nqsd0c76g0\LocalCache\Roaming\ChatGPT\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\OpenAI.ChatGPT-Desktop_2p2nqsd0c76g0\LocalCache\Roaming\ChatGPT\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\botocore\data\backup' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\botocore\data\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\RealtekSemiconductorCorp.RealtekAudioControl_dt26b99r8h8gj\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\SpotifyAB.SpotifyMusic_zpdnekdrzrea0\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\SpotifyAB.SpotifyMusic_zpdnekdrzrea0\LocalCache\Spotify\Default\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\SpotifyAB.SpotifyMusic_zpdnekdrzrea0\LocalCache\Spotify\Default\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\TradingView.Desktop_n534cwy3pjxzj\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\TradingView.Desktop_n534cwy3pjxzj\LocalCache\Roaming\TradingView\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\TradingView.Desktop_n534cwy3pjxzj\LocalCache\Roaming\TradingView\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\TradingView.Desktop_n534cwy3pjxzj\LocalCache\Roaming\TradingView\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Windows.CBSPreview_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\windows.immersivecontrolpanel_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\Windows.PrintDialog_cw5n1h2txyewy\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Packages\windows_ie_ac_001\AC\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\pip\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\prisma-nodejs\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Programs\cursor\resources\app\node_modules\@connectrpc\connect-node\node_modules\undici\lib\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Programs\cursor\resources\app\node_modules\undici\lib\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Programs\cursor\resources\app\node_modules\undici\lib\web\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Roblox\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Roblox\RobloxStudio\WebView2\EBWebView\Default\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Roblox\RobloxStudio\WebView2\EBWebView\Default\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Roblox\Versions\version-1fd40173390f491a\ExtraContent\LuaPackages\Packages\_Index\ApolloClient\ApolloClient\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Roblox\Versions\version-1fd40173390f491a\ExtraContent\LuaPackages\Packages\_Index\SocialLibraries\SocialLibraries\temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Steam\htmlcache\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Steam\htmlcache\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Temp\WinGet\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Temp\_MEI331562\botocore\data\backup' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Local\Temp\_MEI331562\botocore\data\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\LocalLow\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\LocalLow\Adobe\CRLogs\AdobeCRCommon\Logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\LocalLow\webviewdata\2\EBWebView\Default\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\LocalLow\webviewdata\2\EBWebView\Default\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Adobe\UPI\Temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\AnyDesk\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Code\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Code\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Code\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Cursor\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Cursor\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Cursor\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\discord\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\discord\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\discord\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Docker Desktop\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Docker Desktop\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\fnm\aliases\default\node_modules\npm\node_modules\make-fetch-happen\lib\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\fnm\node-versions\v22.13.1\installation\node_modules\npm\node_modules\make-fetch-happen\lib\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\lilybear-desktop\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\lilybear-desktop\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\MetaQuotes\Terminal\915566BA06ADA407569C544CC0D97611\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\MetaQuotes\Terminal\915566BA06ADA407569C544CC0D97611\bases\Default\History\EURUSD\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\MetaQuotes\Terminal\915566BA06ADA407569C544CC0D97611\bases\Default\History\GBPUSD\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\MetaQuotes\Terminal\915566BA06ADA407569C544CC0D97611\bases\Default\History\USDCHF\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\MetaQuotes\Terminal\915566BA06ADA407569C544CC0D97611\bases\Default\History\USDJPY\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\MetaQuotes\Terminal\915566BA06ADA407569C544CC0D97611\bases\OANDA-Live-1\history\EURUSD\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\MetaQuotes\Terminal\915566BA06ADA407569C544CC0D97611\bases\OANDA-Live-1\history\GBPUSD\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\MetaQuotes\Terminal\915566BA06ADA407569C544CC0D97611\bases\OANDA-Live-1\history\USDCHF\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\MetaQuotes\Terminal\915566BA06ADA407569C544CC0D97611\bases\OANDA-Live-1\history\USDJPY\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\MetaQuotes\Terminal\915566BA06ADA407569C544CC0D97611\liveupdate\temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\MetaQuotes\Terminal\915566BA06ADA407569C544CC0D97611\MQL5\Logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\MetaQuotes\Terminal\D0E8209F77C8CF37AD8BF550E51FF075\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\MetaQuotes\Terminal\D0E8209F77C8CF37AD8BF550E51FF075\temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\MetaQuotes\Terminal\D0E8209F77C8CF37AD8BF550E51FF075\bases\Default\History\EURUSD\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\MetaQuotes\Terminal\D0E8209F77C8CF37AD8BF550E51FF075\bases\Default\History\GBPUSD\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\MetaQuotes\Terminal\D0E8209F77C8CF37AD8BF550E51FF075\bases\Default\History\USDCHF\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\MetaQuotes\Terminal\D0E8209F77C8CF37AD8BF550E51FF075\bases\Default\History\USDJPY\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\MetaQuotes\Terminal\D0E8209F77C8CF37AD8BF550E51FF075\bases\MetaQuotes-Demo\history\EURUSD\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\MetaQuotes\Terminal\D0E8209F77C8CF37AD8BF550E51FF075\bases\MetaQuotes-Demo\history\GBPUSD\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\MetaQuotes\Terminal\D0E8209F77C8CF37AD8BF550E51FF075\bases\MetaQuotes-Demo\history\USDCHF\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\MetaQuotes\Terminal\D0E8209F77C8CF37AD8BF550E51FF075\bases\MetaQuotes-Demo\history\USDJPY\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\MetaQuotes\Terminal\D0E8209F77C8CF37AD8BF550E51FF075\MQL5\Logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\MetaQuotes\Terminal\D0E8209F77C8CF37AD8BF550E51FF075\temp\EBWebView\Default\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\MetaQuotes\Terminal\D0E8209F77C8CF37AD8BF550E51FF075\temp\EBWebView\Default\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\MongoDB Compass\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\MongoDB Compass\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Crash Reports\glean\tmp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\datareporting\glean\tmp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\file++++C++Users+sunny+AppData+Local+Microsoft+Windows+INetCache+IE+1FCVL7ZW+pricing[1]\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\http+++localhost+3000\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++android-dot-devsite-v2-prod.appspot.com^partitionKey=%28https%2Candroid.com%29\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++apps.microsoft.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++chat.mistral.ai\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++coinbrain.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++coinmarketcap.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++community.openai.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++conversations.godaddy.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++create.roblox.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++dashboard.godaddy.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++developer.android.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++devforum.roblox.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++dexscreener.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++discussions.apple.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++disneyworld.disney.go.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++fapscfoundation.org\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++firefly.adobe.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++gamedin.xyz\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++goblin.tools\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++mail.google.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++meet.google.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++my.tastytrade.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++onedrive.live.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++outlook.office.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++phemex.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++sso.godaddy.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++trade.oanda.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++unsplash.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++websites.godaddy.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++word-edit.officeapps.live.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++www.coinbase.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++www.epicgames.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++www.facebook.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++www.honeybook.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++www.icloud.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++www.igv.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++www.instagram.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++www.kinguin.net\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++www.logitech.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++www.newport-pleasure.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++www.reddit.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++www.tiktok.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++www.tradingview.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++www.youtube-nocookie.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++www.youtube.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++www.youtube.com^partitionKey=%28https%2Cgoogle.com%29\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++x.com\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\storage\default\https+++youtube.googleapis.com^partitionKey=%28https%2Cgoogle.com%29\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Mozilla\Firefox\Profiles\szt8u8oo.default-release\weave\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\npm\node_modules\npm\node_modules\make-fetch-happen\lib\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\make-fetch-happen\lib\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\ProcessLasso\temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\pypoetry\venv\Lib\site-packages\poetry\console\commands\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Python\Python313\site-packages\botocore\data\backup' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Python\Python313\site-packages\botocore\data\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\rsilauncher\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\rsilauncher\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\rsilauncher\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\UnityHub\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\UnityHub\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Windsurf\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Windsurf\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Windsurf\Shared Dictionary\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\AppData\Roaming\Zoom\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\LilithOS_Backup\LilithOS_Windows_20250629_143951\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\mpl-token-metadata\.git\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\mpl-token-metadata\metaplex\.git\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\OneDrive\0 Day Exploits\KMSpico 10.2.0\Portable\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\OneDrive\Documents\Gaming\DS4Windows\Logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\OneDrive\Documents\Gaming\My games\Borderlands 2\WillowGame\Logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\OneDrive\Documents\Gaming\My games\Borderlands 3\Saved\Logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\OneDrive\Documents\Gaming\My games\Crossout\Logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\OneDrive\Documents\My Games\Borderlands 2\WillowGame\Logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\OneDrive\Documents\My Games\Borderlands 3\Saved\Logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\OneDrive\Documents\Rockstar Games\Social Club\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\OneDrive\Documents\Rockstar Games\Social Club\Launcher\Renderer\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\OneDrive\Documents\Software Testing\Tests\cypress-realworld-app\.git\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\OneDrive\Documents\Software Testing\Tests\sl1\.git\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\OneDrive\Documents\Software Testing\Tests\sl1\config\node_modules\tmp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\OneDrive\Documents\Software Testing\Tests\sl1\config\selenium\datareporting\glean\tmp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\OneDrive\Documents\Software Testing\Tests\sl1\node_modules\tmp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\OneDrive\Documents\Software Testing\Tests\testingOne\node_modules\tmp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\OneDrive\Documents\Software Testing\Tests\testRigor\.git\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\OneDrive\Documents\Software Testing\Tests\webstaurant1\.git\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\phantom\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\phantom\tools\$PHANTOM_ROOT\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\phantom\tools\impacket\.git\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\temp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\.git\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\AthenaMist-Forex\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\dashboard\node_modules\@aws-amplify\core\dist\cjs\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\dashboard\node_modules\@aws-amplify\core\dist\cjs\singleton\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\dashboard\node_modules\@aws-amplify\core\dist\esm\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\dashboard\node_modules\@aws-amplify\core\dist\esm\singleton\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\dashboard\node_modules\@aws-amplify\core\src\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\dashboard\node_modules\@aws-amplify\core\src\singleton\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\dashboard\node_modules\@smithy\util-endpoints\dist-cjs\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\dashboard\node_modules\@smithy\util-endpoints\dist-es\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\dashboard\node_modules\@smithy\util-endpoints\dist-types\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\dashboard\node_modules\@smithy\util-endpoints\dist-types\ts3.4\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\dashboard\node_modules\webpack\lib\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\tmp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\core\dist\cjs\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\core\dist\cjs\singleton\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\core\dist\esm\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\core\dist\esm\singleton\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\core\src\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\core\src\singleton\Cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\data-construct\node_modules\@aws-sdk\client-bedrock-runtime\node_modules\@smithy\util-endpoints\dist-cjs\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\data-construct\node_modules\@aws-sdk\client-bedrock-runtime\node_modules\@smithy\util-endpoints\dist-es\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\data-construct\node_modules\@aws-sdk\client-bedrock-runtime\node_modules\@smithy\util-endpoints\dist-types\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\data-construct\node_modules\@aws-sdk\client-bedrock-runtime\node_modules\@smithy\util-endpoints\dist-types\ts3.4\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\data-construct\node_modules\@aws-sdk\client-sts\node_modules\@smithy\util-endpoints\dist-cjs\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\data-construct\node_modules\@aws-sdk\client-sts\node_modules\@smithy\util-endpoints\dist-es\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\data-construct\node_modules\@aws-sdk\client-sts\node_modules\@smithy\util-endpoints\dist-types\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\data-construct\node_modules\@aws-sdk\client-sts\node_modules\@smithy\util-endpoints\dist-types\ts3.4\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\data-construct\node_modules\@aws-sdk\nested-clients\node_modules\@smithy\util-endpoints\dist-cjs\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\data-construct\node_modules\@aws-sdk\nested-clients\node_modules\@smithy\util-endpoints\dist-es\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\data-construct\node_modules\@aws-sdk\nested-clients\node_modules\@smithy\util-endpoints\dist-types\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\data-construct\node_modules\@aws-sdk\nested-clients\node_modules\@smithy\util-endpoints\dist-types\ts3.4\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\data-construct\node_modules\@smithy\util-endpoints\dist-cjs\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\data-construct\node_modules\@smithy\util-endpoints\dist-es\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\data-construct\node_modules\@smithy\util-endpoints\dist-types\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\data-construct\node_modules\@smithy\util-endpoints\dist-types\ts3.4\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\graphql-api-construct\node_modules\@aws-sdk\client-bedrock-runtime\node_modules\@smithy\util-endpoints\dist-cjs\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\graphql-api-construct\node_modules\@aws-sdk\client-bedrock-runtime\node_modules\@smithy\util-endpoints\dist-es\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\graphql-api-construct\node_modules\@aws-sdk\client-bedrock-runtime\node_modules\@smithy\util-endpoints\dist-types\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\graphql-api-construct\node_modules\@aws-sdk\client-bedrock-runtime\node_modules\@smithy\util-endpoints\dist-types\ts3.4\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\graphql-api-construct\node_modules\@aws-sdk\client-sts\node_modules\@smithy\util-endpoints\dist-cjs\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\graphql-api-construct\node_modules\@aws-sdk\client-sts\node_modules\@smithy\util-endpoints\dist-es\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\graphql-api-construct\node_modules\@aws-sdk\client-sts\node_modules\@smithy\util-endpoints\dist-types\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\graphql-api-construct\node_modules\@aws-sdk\client-sts\node_modules\@smithy\util-endpoints\dist-types\ts3.4\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\graphql-api-construct\node_modules\@aws-sdk\nested-clients\node_modules\@smithy\util-endpoints\dist-cjs\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\graphql-api-construct\node_modules\@aws-sdk\nested-clients\node_modules\@smithy\util-endpoints\dist-es\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\graphql-api-construct\node_modules\@aws-sdk\nested-clients\node_modules\@smithy\util-endpoints\dist-types\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\graphql-api-construct\node_modules\@aws-sdk\nested-clients\node_modules\@smithy\util-endpoints\dist-types\ts3.4\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\graphql-api-construct\node_modules\@aws-sdk\util-endpoints\node_modules\@smithy\util-endpoints\dist-cjs\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\graphql-api-construct\node_modules\@aws-sdk\util-endpoints\node_modules\@smithy\util-endpoints\dist-es\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\graphql-api-construct\node_modules\@aws-sdk\util-endpoints\node_modules\@smithy\util-endpoints\dist-types\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\graphql-api-construct\node_modules\@aws-sdk\util-endpoints\node_modules\@smithy\util-endpoints\dist-types\ts3.4\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\graphql-api-construct\node_modules\@smithy\util-endpoints\dist-cjs\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\graphql-api-construct\node_modules\@smithy\util-endpoints\dist-es\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\graphql-api-construct\node_modules\@smithy\util-endpoints\dist-types\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\graphql-api-construct\node_modules\@smithy\util-endpoints\dist-types\ts3.4\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\graphql-schema-generator\node_modules\@smithy\util-endpoints\dist-cjs\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\graphql-schema-generator\node_modules\@smithy\util-endpoints\dist-es\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\graphql-schema-generator\node_modules\@smithy\util-endpoints\dist-types\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-amplify\graphql-schema-generator\node_modules\@smithy\util-endpoints\dist-types\ts3.4\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-sdk\client-ec2\node_modules\@smithy\util-endpoints\dist-cjs\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-sdk\client-ec2\node_modules\@smithy\util-endpoints\dist-es\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-sdk\client-ec2\node_modules\@smithy\util-endpoints\dist-types\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-sdk\client-ec2\node_modules\@smithy\util-endpoints\dist-types\ts3.4\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-sdk\client-firehose\node_modules\@smithy\util-endpoints\dist-cjs\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-sdk\client-firehose\node_modules\@smithy\util-endpoints\dist-es\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-sdk\client-firehose\node_modules\@smithy\util-endpoints\dist-types\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-sdk\client-firehose\node_modules\@smithy\util-endpoints\dist-types\ts3.4\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-sdk\client-iam\node_modules\@smithy\util-endpoints\dist-cjs\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-sdk\client-iam\node_modules\@smithy\util-endpoints\dist-es\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-sdk\client-iam\node_modules\@smithy\util-endpoints\dist-types\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-sdk\client-iam\node_modules\@smithy\util-endpoints\dist-types\ts3.4\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-sdk\client-kinesis\node_modules\@smithy\util-endpoints\dist-cjs\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-sdk\client-kinesis\node_modules\@smithy\util-endpoints\dist-es\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-sdk\client-kinesis\node_modules\@smithy\util-endpoints\dist-types\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-sdk\client-kinesis\node_modules\@smithy\util-endpoints\dist-types\ts3.4\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-sdk\client-personalize-events\node_modules\@smithy\util-endpoints\dist-cjs\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-sdk\client-personalize-events\node_modules\@smithy\util-endpoints\dist-es\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-sdk\client-personalize-events\node_modules\@smithy\util-endpoints\dist-types\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-sdk\client-personalize-events\node_modules\@smithy\util-endpoints\dist-types\ts3.4\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-sdk\client-rds\node_modules\@smithy\util-endpoints\dist-cjs\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-sdk\client-rds\node_modules\@smithy\util-endpoints\dist-es\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-sdk\client-rds\node_modules\@smithy\util-endpoints\dist-types\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-sdk\client-rds\node_modules\@smithy\util-endpoints\dist-types\ts3.4\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-sdk\client-sso-oidc\node_modules\@smithy\util-endpoints\dist-cjs\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-sdk\client-sso-oidc\node_modules\@smithy\util-endpoints\dist-es\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-sdk\client-sso-oidc\node_modules\@smithy\util-endpoints\dist-types\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@aws-sdk\client-sso-oidc\node_modules\@smithy\util-endpoints\dist-types\ts3.4\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@smithy\util-endpoints\dist-cjs\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@smithy\util-endpoints\dist-es\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@smithy\util-endpoints\dist-types\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\AthenaMist-Blended\node_modules\@smithy\util-endpoints\dist-types\ts3.4\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\MKZenith\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\MKZenith\.git\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\MKZenith\node_modules\tmp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\MKZenith\node_modules\@ledgerhq\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\MKZenith\node_modules\@openzeppelin\hardhat-upgrades\node_modules\undici\lib\web\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\MKZenith\node_modules\@react-native\debugger-frontend\dist\third-party\front_end\models\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\MKZenith\node_modules\@smithy\util-endpoints\dist-cjs\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\MKZenith\node_modules\@smithy\util-endpoints\dist-es\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\MKZenith\node_modules\@smithy\util-endpoints\dist-types\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\MKZenith\node_modules\@smithy\util-endpoints\dist-types\ts3.4\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\MKZenith\node_modules\metro-file-map\src\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\MKZenith\node_modules\tmp-promise\node_modules\tmp' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\MKZenith\node_modules\undici\lib\cache' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\Purrify\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\Purrify\.git\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\Saved Games\Purrify\src\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\ShadowFlowerConsole\Aletheia\.git\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\ShadowFlowerConsole\Aphrodite\.git\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\ShadowFlowerConsole\Bastet\.git\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\ShadowFlowerConsole\Freya\.git\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\ShadowFlowerConsole\Hecate\.git\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\ShadowFlowerConsole\Inanna\.git\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\ShadowFlowerConsole\Isis\.git\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\ShadowFlowerConsole\Kali\.git\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\ShadowFlowerConsole\Lilith\.git\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\ShadowFlowerConsole\Morrigan\.git\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\ShadowFlowerConsole\Persephone\.git\logs' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'C:\Users\sunny\ShadowFlowerConsole\Yemaya\.git\logs' -Recurse -Force -ErrorAction SilentlyContinue
# Enhanced optimizations based on comprehensive scan
# Clean login patterns and session data
Remove-Item -Path $env:LOCALAPPDATA\Microsoft\Windows\INetCache\* -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path $env:LOCALAPPDATA\Microsoft\Windows\History\* -Recurse -Force -ErrorAction SilentlyContinue
# Optimize most used files
Remove-Item -Path $env:LOCALAPPDATA\Microsoft\Windows\Explorer\thumbcache_*.db -Force -ErrorAction SilentlyContinue
# Clean user directories
Remove-Item -Path $env:TEMP\* -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path $env:LOCALAPPDATA\Temp\* -Recurse -Force -ErrorAction SilentlyContinue
# Clean program installation caches
Get-ChildItem 'C:\Program Files' -Recurse -Include '*.tmp','*.cache','*.log' | Remove-Item -Force -ErrorAction SilentlyContinue
Get-ChildItem 'C:\Program Files (x86)' -Recurse -Include '*.tmp','*.cache','*.log' | Remove-Item -Force -ErrorAction SilentlyContinue
# Optimize startup items
Get-CimInstance Win32_StartupCommand | Where-Object { $_.Location -notlike '*Windows*' } | ForEach-Object { Remove-ItemProperty -Path $_.Command -Name $_.Name -ErrorAction SilentlyContinue }
Write-Host 'Purrify optimization complete!' -ForegroundColor Green