"""
Script Generator for Machine-Specific System Optimization

Generates custom PowerShell (Windows) or Bash (Linux/macOS) scripts
to further optimize the system based on scan results and LilithOS technology.
"""

import os
import platform
from pathlib import Path
from typing import Dict, Any
from loguru import logger

class ScriptGenerator:
    """
    Generates machine-specific optimization scripts based on scan results.
    Supports PowerShell (Windows) and Bash (Linux/macOS).
    Integrates LilithOS technology if detected.
    """
    
    def __init__(self, scan_results: Dict[str, Any], output_dir: str = "Purrify_Optimizations"):
        self.scan_results = scan_results
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)
        self.system = platform.system().lower()
        logger.info(f"ScriptGenerator initialized for {self.system}")
    
    def generate(self) -> str:
        """Generate and save the optimization script. Returns the script path."""
        if self.system == "windows":
            script_content = self._generate_powershell_script()
            script_path = self.output_dir / "purrify_optimize.ps1"
        else:
            script_content = self._generate_bash_script()
            script_path = self.output_dir / "purrify_optimize.sh"
        
        with open(script_path, "w", encoding="utf-8") as f:
            f.write(script_content)
        logger.info(f"Optimization script generated: {script_path}")
        return str(script_path)
    
    def _generate_powershell_script(self) -> str:
        """Generate a PowerShell script for Windows optimization."""
        lines = [
            "# Purrify Machine-Specific Optimization Script (PowerShell)",
            "# Generated by Purrify with LilithOS technology",
            "$ErrorActionPreference = 'Stop'",
            "Write-Host 'Running Purrify system optimizations...' -ForegroundColor Cyan"
        ]
        
        # Startup optimization
        lines.append("# Disable unnecessary startup items")
        lines.append("Get-CimInstance Win32_StartupCommand | Where-Object { $_.Location -notlike '*Windows*' } | ForEach-Object { Write-Host 'Disabling:' $_.Name; Remove-ItemProperty -Path $_.Command -Name $_.Name -ErrorAction SilentlyContinue }")
        
        # Service optimization
        lines.append("# Set unnecessary services to Manual")
        lines.append("$services = @('DiagTrack','MapsBroker','WSearch','Fax','XblGameSave','XboxNetApiSvc','WMPNetworkSvc')")
        lines.append("foreach ($svc in $services) { Set-Service -Name $svc -StartupType Manual -ErrorAction SilentlyContinue }")
        
        # Registry tweaks (Windows 11 performance)
        lines.append("# Windows 11 performance registry tweaks")
        lines.append("Set-ItemProperty -Path 'HKCU:Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Serialize' -Name 'StartupDelayInMSec' -Value 0 -Force")
        lines.append("Set-ItemProperty -Path 'HKLM:SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' -Name 'EnableLUA' -Value 0 -Force")
        
        # Disk cleanup
        lines.append("# Clean up temp files and system cache")
        lines.append("Remove-Item -Path $env:TEMP\\* -Recurse -Force -ErrorAction SilentlyContinue")
        lines.append("Remove-Item -Path C:\\Windows\\Temp\\* -Recurse -Force -ErrorAction SilentlyContinue")
        
        # LilithOS-specific enhancements
        lilithos = self.scan_results.get("lilithos_references", {})
        if lilithos.get("paths_found"):
            lines.append("# LilithOS-specific optimizations")
            for path in lilithos["paths_found"]:
                lines.append(f"# Clean LilithOS cache: {path}")
                lines.append(f"Remove-Item -Path '{path}\\*' -Recurse -Force -ErrorAction SilentlyContinue")
        
        # Redundant folders
        redundant = self.scan_results.get("redundant_folders", {})
        if redundant.get("folders_found"):
            lines.append("# Remove redundant folders")
            for folder in redundant["folders_found"]:
                lines.append(f"Remove-Item -Path '{folder['path']}' -Recurse -Force -ErrorAction SilentlyContinue")
        
        # Enhanced optimizations based on scan results
        lines.append("# Enhanced optimizations based on comprehensive scan")
        
        # Login patterns optimization
        login_patterns = self.scan_results.get("login_patterns", {})
        if login_patterns.get("count", 0) > 0:
            lines.append("# Clean login patterns and session data")
            lines.append("Remove-Item -Path $env:LOCALAPPDATA\\Microsoft\\Windows\\INetCache\\* -Recurse -Force -ErrorAction SilentlyContinue")
            lines.append("Remove-Item -Path $env:LOCALAPPDATA\\Microsoft\\Windows\\History\\* -Recurse -Force -ErrorAction SilentlyContinue")
        
        # Most used files optimization
        most_used = self.scan_results.get("most_used_files", {})
        if most_used.get("count", 0) > 0:
            lines.append("# Optimize most used files")
            lines.append("Remove-Item -Path $env:LOCALAPPDATA\\Microsoft\\Windows\\Explorer\\thumbcache_*.db -Force -ErrorAction SilentlyContinue")
        
        # User directories optimization
        user_dirs = self.scan_results.get("user_directories", {})
        if user_dirs.get("count", 0) > 0:
            lines.append("# Clean user directories")
            lines.append("Remove-Item -Path $env:TEMP\\* -Recurse -Force -ErrorAction SilentlyContinue")
            lines.append("Remove-Item -Path $env:LOCALAPPDATA\\Temp\\* -Recurse -Force -ErrorAction SilentlyContinue")
        
        # Program installations optimization
        programs = self.scan_results.get("program_installations", {})
        if programs.get("count", 0) > 0:
            lines.append("# Clean program installation caches")
            lines.append("Get-ChildItem 'C:\\Program Files' -Recurse -Include '*.tmp','*.cache','*.log' | Remove-Item -Force -ErrorAction SilentlyContinue")
            lines.append("Get-ChildItem 'C:\\Program Files (x86)' -Recurse -Include '*.tmp','*.cache','*.log' | Remove-Item -Force -ErrorAction SilentlyContinue")
        
        # Startup and services optimization
        startup = self.scan_results.get("startup_and_services", {})
        if startup.get("count", 0) > 0:
            lines.append("# Optimize startup items")
            lines.append("Get-CimInstance Win32_StartupCommand | Where-Object { $_.Location -notlike '*Windows*' } | ForEach-Object { Remove-ItemProperty -Path $_.Command -Name $_.Name -ErrorAction SilentlyContinue }")
        
        lines.append("Write-Host 'Purrify optimization complete!' -ForegroundColor Green")
        return "\n".join(lines)
    
    def _generate_bash_script(self) -> str:
        """Generate a Bash script for Linux/macOS optimization."""
        lines = [
            "#!/bin/bash",
            "# Purrify Machine-Specific Optimization Script (Bash)",
            "# Generated by Purrify with LilithOS technology",
            "set -e",
            "echo 'Running Purrify system optimizations...'"
        ]
        
        # Startup optimization (macOS/Linux)
        lines.append("# Disable unnecessary launch agents (macOS)")
        lines.append("launchctl list | grep -v com.apple | awk '{print $3}' | xargs -I {} launchctl remove {} || true")
        
        # Clean temp/cache
        lines.append("# Clean up temp and cache files")
        lines.append("rm -rf /tmp/* $HOME/Library/Caches/* $HOME/.cache/*")
        
        # LilithOS-specific enhancements
        lilithos = self.scan_results.get("lilithos_references", {})
        if lilithos.get("paths_found"):
            lines.append("# LilithOS-specific optimizations")
            for path in lilithos["paths_found"]:
                lines.append(f"# Clean LilithOS cache: {path}")
                lines.append(f"rm -rf '{path}'/*")
        
        # Redundant folders
        redundant = self.scan_results.get("redundant_folders", {})
        if redundant.get("folders_found"):
            lines.append("# Remove redundant folders")
            for folder in redundant["folders_found"]:
                lines.append(f"rm -rf '{folder['path']}'")
        
        lines.append("echo 'Purrify optimization complete!'")
        return "\n".join(lines) 